services:
  rotoplas:
    # image: myapp:latest
    restart: always
    build:
      context: .
      network: host
    ports:
      - "8080:8080"
    volumes:
      - ./files:/usr/src/app/files
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sietemachete
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
