services:
  rotoplas:
    # image: myapp:latest
    build: 
      context: .
      network: host
    ports:
      - "8080:80"
    environment:
      - MONGODB_URI=mongodb://root:example@localhost:27017/rotoplas
    volumes:
      - ./files:/usr/src/app/files
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
