services:
  rotoplas:
    # image: myapp:latest
    restart: always
    build:
      context: .
      network: host
    ports:
      - "8080:8080"
    volumes:
      - ./files:/usr/src/app/files
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
     - "27017:27017"
volumes:
  mongo-data:
