apiVersion: v1
kind: Service
metadata:
  name: rotoplas
  namespace: rotoplas
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: rotoplas
---
apiVersion: v1
kind: Service
metadata:
  name: mysql 
  namespace: rotoplas
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30332
  selector:
    app: mysql
